import About from './About'
import ContactMe from './ContactMe'
import Navbar from './Navbar'
import Projects from './Projects'
import Social from './Social'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Portfolio(Aniket)',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>  
          <Navbar />
          <div className={inter.className}>{children}</div>
          <About/>
          <Projects/>
          <ContactMe/>
          <Social/>
      </body>
    </html>
  )
}
