import Navbar from './components/Navbar'
import Projects from './components/Projects'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Portfolio(Aniket)',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <div>
          <Navbar />
          <div className={inter.className}>{children}</div>
          <Projects/>
        </div>
      </body>
    </html>
  )
}
